project:
  type: website
website:
  title: "Ime Essien Website"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: website.qmd
      - text: "About" 
        file: about.qmd 
      - text: "Example analysis" 
        file: example.qmd
      - text: "More"
        menu:
        - website.qmd
        - about.qmd 
        - example.qmd   
format:
  html:
    theme: simplex
    toc: true
    css: styles.css
    code-overflow: wrap

editor: source

execute:
  freeze: auto